micronaut:
  server:
    port: 8081
  application:
    name: key_manager_grpc

datasources:
  default:
    url: ${DB_URI:`jdbc:mysql://localhost:3306/key_manager_grpc?serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:MYSQL}
jpa.default.properties.hibernate.hbm2ddl.auto: update

itau.contas.url: ${ITAU_URL:`http://localhost:9091`}
bcb.pix.url: ${BCB_URL:`http://localhost:8082`}